<?php

require_once  'DataAccess.inc';
//use DataAccess;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Grade
 *
 * @author kami
 */
class Grade {

    public $GradeId = 1;
    public $Value;
    public $StudentClassRoom;
    public $GradeType;

}
