<?php

require_once 'DataAccess.inc';
//use DataAccess;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of GradeType
 *
 * @author kami
 */
class GradeType {

    public $GradeTypeId = 1;
    public $Name;
    public $Min;
    public $Max;
    public $Pass;
    public $DefinedValues;

}
