<?php

require_once  'DataAccess.inc';
//use DataAccess;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Teacher
 *
 * @author kami
 */
class QuestionChoice {

    public $QuestionChoiceId = 1;
    public $Content;
    public $Question;
}
