<?php

require_once 'DataAccess.inc';
//use DataAccess;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Teacher
 *
 * @author kami
 */
class Teacher {

    public $TeacherId = 1;
    public $Name;
    public $Family;
    public $Username;
    public $Passwd;
    public $CodeMelli;

}
